### ISSUE TITLE
PImage.resize() always causes crash

### ISSUE THREAD

**Issue by xstreck1** [processing/processing-android-archive#46] opened 2013-07-15 14:25 UTC
calling the method PImage.resize() causes the application to crash (also referenced here: https://forum.processing.org/topic/problem-with-pimage-resize ) when run on Android with the following error:

FATAL EXCEPTION: Animation Thread
java.lang.NullPointerException
    at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:344)
    at processing.core.PImage.resize(Unknown Source)
    at processing.test.CreateImage.CreateImage.setup(CreateImage.java:35)
    at processing.core.PApplet.handleDraw(Unknown Source)
    at processing.core.PGraphicsAndroid2D.requestDraw(Unknown Source)
    at processing.core.PApplet.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:1019)

For a reference the following extension of the CreateImage example can be used:

```
PImage img;
void setup() 
{
  size(200, 200);
  img = createImage(120, 120, ARGB);
  for(int i=0; i < img.pixels.length; i++) {
    img.pixels[i] = color(0, 90, 102, i%img.width * 2); 
  }
  img.resize(150,100);
}
void draw() 
{
  background(204);
  image(img, 33, 33);
  image(img, mouseX-60, mouseY-60);
}
```

Although this may be replaced with call of the image() method with height and width specified, for animating sprites this adds unnecessary computational burden to rescale an image 30 times a second.

**Comment by jeffThompson** [comment] 2013-07-15 14:31
Not having my tablet in front of me, I believe the error might be with you accessing the image's pixels. While you can do this the way you have it in the desktop version, if memory serves the Android mode will cause an NPE if you don't include img.loadPixels() and img.updatePixels() first.

**Comment by xstreck1** [comment] 2013-07-15 14:45
I have chosen the example so no external file is needed, however if the image is created using the loadImage() method (and pixels are not accessed), the crash occurs as well. E.g. extension of the LoadDisplayImage example:

```
PImage img;  // Declare variable "a" of type PImage

void setup() {
  size(640, 360);
  // The image file must be in the data folder of the current sketch 
  // to load successfully
  img = loadImage("moonwalk.jpg");  // Load the image into the program  
  img.resize(100,100);
}

void draw() {
  // Displays the image at its actual size at point (0,0)
  image(img, 0, 0);
  // Displays the image at point (0, height/2) at half of its size
  image(img, 0, height/2, img.width/2, img.height/2);
}
```

crashes with:
FATAL EXCEPTION: Animation Thread
java.lang.NullPointerException
    at android.graphics.Bitmap.checkPixelsAccess(Bitmap.java:834)
    at android.graphics.Bitmap.setPixels(Bitmap.java:892)
    at processing.core.PGraphicsAndroid2D.imageImpl(Unknown Source)
    at processing.core.PGraphics.image(Unknown Source)
    at processing.core.PApplet.image(Unknown Source)
    at processing.test.loaddisplayimage.LoadDisplayImage.draw(LoadDisplayImage.java:41)
    at processing.core.PApplet.handleDraw(Unknown Source)
    at processing.core.PGraphicsAndroid2D.requestDraw(Unknown Source)
    at processing.core.PApplet.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:1019)

But, actually, based on your suggestion I have tried adding pixel manipulation methods to the code and the following version (img.loadPixels() is added after resize) works:

```
PImage img;  // Declare variable "a" of type PImage

void setup() {
  size(640, 360);
  // The image file must be in the data folder of the current sketch 
  // to load successfully
  img = loadImage("moonwalk.jpg");  // Load the image into the program  
  img.resize(100,100);
  img.loadPixels();
}

void draw() {
  // Displays the image at its actual size at point (0,0)
  image(img, 0, 0);
  // Displays the image at point (0, height/2) at half of its size
  image(img, 0, height/2, img.width/2, img.height/2);
}
```

I am not familiar with method Processing internally works with images, but I assume that the requirement the explicit call of img.loadPixels() is not intentional.

**Comment by GKFX** [comment] 2014-05-09 18:06
Duplicate of #22.

**Closed as completed** 2014-05-10 13:30 UTC
Labels: duplicate

**Comment by PandaBalls** [comment] 2016-09-14 12:43
why it is closed ? i didn't find the solution for this resize() problem. i just got the same issue.

**Comment by GKFX** [comment] 2016-09-14 12:45
It's not really closed as in fixed, it's closed as a duplicate. The report is still open at #22.

**Comment by GKFX** [comment] 2016-09-14 12:47
Actually, it's processing/processing-android#21; this repository is archived.
