### ISSUE TITLE
App crashed in P3D mode on Nexus 4 Android 4.2.2

### ISSUE THREAD

**Issue by emnullfuenf** [processing/processing-android-archive#40] opened 2013-05-30 11:15 UTC
When adding P3D in size() even a basic app crashes at start:

Error:
Smooth is not supported by this hardware (or driver)

smooth(); isn't called in the sketch. Adding noSmooth(); to the sketch does not help.

Device:
Nexus 4
Android 4.2.2

Processing 2.0b8

**Comment by boubpopsyteam** [comment] 2013-05-30 16:55
Duplicate of #3 :)

**Closed as completed** 2013-05-30 19:16 UTC
Labels: duplicate
